name: theme_customizer
description: TODO
version: 0.0.1
homepage: https://github.com/shilangyu/theme_customizer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
